package twitterclient;

import com.sun.jersey.api.client.Client;
import com.sun.jersey.api.client.UniformInterfaceException;
import com.sun.jersey.api.client.WebResource;
import com.sun.jersey.api.representation.Form;
import com.sun.jersey.oauth.client.OAuthClientFilter;
import com.sun.jersey.oauth.signature.OAuthParameters;
import com.sun.jersey.oauth.signature.OAuthSecrets;
import java.awt.Color;
import java.awt.EventQueue;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.net.URLEncoder;
import java.util.Timer;
import java.util.StringTokenizer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.swing.ImageIcon;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.HyperlinkEvent;
import javax.swing.text.Document;
import javax.ws.rs.core.MultivaluedMap;
import twitter.twitteroauth.twitterresponse.StatusType;
import twitter.twitteroauth.twitterresponse.Statuses;
import twitter.twitteroauth.twitterresponse.UserType;
import javax.swing.text.Document;


/**
 * @author Kevin Doyle
 * @email  kfrdoyle[at]gmail[dot]com
 */
public class TwitterJFrame extends javax.swing.JFrame {

StringBuilder strGetFriendsTimeline= new StringBuilder();
static URL oAuthURL=null;//comes from inner class AthoriseConsumer method
static URL oldURL=null;
 static Form requestTokenResponse=null;

    public TwitterJFrame() {
        System.out.println("In TwitterJFrame Constructor");
        /** TwitterJFrame class constructor */
        initComponents(); //Step (1)
        toggleUIButtons(false);//disable UI Buttons

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                collectLoginData(); //Step (2)
            }
        });

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    loadAWebPage(); //Step (3)
                } catch (IOException ex) {
                    Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });


/**
        try {
            loginUser(); //OAuth Login only, dont retrieve resourses yet
           System.out.println("After call to loginUser method");
        } catch (MalformedURLException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
**/

    }    /**End of TwitterJFrame class constructor**/

      public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                System.out.println("In main");
                new TwitterJFrame().setVisible(true);
            }
        });
    }

    private void collectLoginData() {
        System.out.println("In collectLoginData Method");
        client = new TwitterClient();
        try {
            client.login();
//             System.out.println("After client.login method local ststic variableURL=: "+oAuthURL.toString());
        } catch (IOException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UniformInterfaceException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

      private  void loadAWebPage() throws IOException{
          System.out.println("In start of loadAWebPage method");

          oldURL=oAuthURL;//keep old url for back button
    URL url =new URL(oAuthURL.toString());
    Document doc =jEPWeb.getDocument();
      try {
        jEPWeb.setPage(url);
      } catch (IOException ioException) {
        System.out.println("Error following link");

        jEPWeb.setDocument(doc);
      }
      System.out.println("Exiting LoadAWebPage method");
}


    /** This method is called from within the constructor to
     * initialize the form.WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBaseLayer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToggleBTimeLine = new javax.swing.JToggleButton();
        jToggleBMentions = new javax.swing.JToggleButton();
        jToggleBMessages = new javax.swing.JToggleButton();
        jToggleBLists = new javax.swing.JToggleButton();
        jToggleBProfiles = new javax.swing.JToggleButton();
        jToggleBSearch = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPPhotoHandle = new javax.swing.JPanel();
        jLUserIcon = new javax.swing.JLabel();
        jLTwitterHandle = new javax.swing.JLabel();
        jLStatusLabel = new javax.swing.JLabel();
        jLLatestTweet = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEPWeb = new javax.swing.JEditorPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPGetVerifierNum = new javax.swing.JPanel();
        jTFrequestTokenResponse = new javax.swing.JTextField();
        jBGotRequestToken = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPTweetStatusUpdate = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("___ Project Preachan___");

        jPBaseLayer.setBackground(new java.awt.Color(51, 51, 255));
        jPBaseLayer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPBaseLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        System.out.println("In initComponents method");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(3276, 32767));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleBTimeLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_time_line.gif"))); // NOI18N
        jToggleBTimeLine.setText("Time Line");
        jToggleBTimeLine.setSelected(false);
        jToggleBTimeLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBTimeLineActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBTimeLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 190, -1));

        jToggleBMentions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_mentions.gif"))); // NOI18N
        jToggleBMentions.setText("Mentions");
        jToggleBMentions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBMentionsActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBMentions, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 59, 190, -1));

        jToggleBMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_messages.gif"))); // NOI18N
        jToggleBMessages.setText("Messages");
        jToggleBMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBMessagesActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 106, 190, -1));

        jToggleBLists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_lists.gif"))); // NOI18N
        jToggleBLists.setText("Lists");
        jToggleBLists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBListsActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBLists, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 153, 190, -1));

        jToggleBProfiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_profile.gif"))); // NOI18N
        jToggleBProfiles.setText("Profile");
        jToggleBProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBProfilesActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBProfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 200, 190, -1));

        jToggleBSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_search.gif"))); // NOI18N
        jToggleBSearch.setText("Search");
        jToggleBSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleBSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleBSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 247, 190, -1));

        jPBaseLayer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 217, 302));

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel4.setEnabled(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/logo.gif"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 12, -1, -1));

        jLabel1.setText("Kevin Doyle © 2011");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 78, -1, -1));

        jPBaseLayer.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 217, 150));

        jPPhotoHandle.setBackground(new java.awt.Color(102, 153, 255));
        jPPhotoHandle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLUserIcon.setText("photo");
        jLUserIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLUserIcon.setMaximumSize(new java.awt.Dimension(48, 48));
        jLUserIcon.setMinimumSize(new java.awt.Dimension(48, 48));
        jLUserIcon.setPreferredSize(new java.awt.Dimension(48, 48));

        jLTwitterHandle.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLTwitterHandle.setForeground(new java.awt.Color(0, 0, 255));
        jLTwitterHandle.setText("Twitter Handle");

        jLStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLStatusLabel.setForeground(new java.awt.Color(0, 0, 255));
        jLStatusLabel.setText("Status:");

        jLLatestTweet.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLLatestTweet.setForeground(new java.awt.Color(0, 0, 255));
        jLLatestTweet.setText("status");

        javax.swing.GroupLayout jPPhotoHandleLayout = new javax.swing.GroupLayout(jPPhotoHandle);
        jPPhotoHandle.setLayout(jPPhotoHandleLayout);
        jPPhotoHandleLayout.setHorizontalGroup(
            jPPhotoHandleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPhotoHandleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPPhotoHandleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTwitterHandle)
                    .addGroup(jPPhotoHandleLayout.createSequentialGroup()
                        .addComponent(jLStatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLLatestTweet)))
                .addContainerGap(997, Short.MAX_VALUE))
        );
        jPPhotoHandleLayout.setVerticalGroup(
            jPPhotoHandleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPhotoHandleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPPhotoHandleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPPhotoHandleLayout.createSequentialGroup()
                        .addComponent(jLUserIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPPhotoHandleLayout.createSequentialGroup()
                        .addComponent(jLTwitterHandle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPPhotoHandleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStatusLabel)
                            .addComponent(jLLatestTweet))
                        .addContainerGap(13, Short.MAX_VALUE))))
        );

        jPBaseLayer.add(jPPhotoHandle, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jScrollPane1.setBorder(null);

        jEPWeb.setBackground(new java.awt.Color(204, 204, 255));
        jEPWeb.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jEPWeb.setContentType("text/html");
        jEPWeb.setEditable(false);
        jEPWeb.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEPWebHyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEPWeb);

        jPBaseLayer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 940, 470));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 102));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTFrequestTokenResponse.setFont(new java.awt.Font("Tahoma", 1, 14));

        jBGotRequestToken.setText("OK");
        jBGotRequestToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGotRequestTokenActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter 8 digit number, then click [OK]");

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGetVerifierNumLayout = new javax.swing.GroupLayout(jPGetVerifierNum);
        jPGetVerifierNum.setLayout(jPGetVerifierNumLayout);
        jPGetVerifierNumLayout.setHorizontalGroup(
            jPGetVerifierNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGetVerifierNumLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addGroup(jPGetVerifierNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFrequestTokenResponse, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jBGotRequestToken, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jButton1)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPGetVerifierNumLayout.setVerticalGroup(
            jPGetVerifierNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGetVerifierNumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(jPGetVerifierNumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFrequestTokenResponse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBGotRequestToken, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPGetVerifierNum.setBounds(0, 0, 1170, 80);
        jLayeredPane1.add(jPGetVerifierNum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterclient/icon_tweet.gif"))); // NOI18N
        jButton2.setText("  Tweet!");
        jButton2.setMaximumSize(new java.awt.Dimension(104, 41));
        jButton2.setMinimumSize(new java.awt.Dimension(104, 41));
        jButton2.setPreferredSize(new java.awt.Dimension(101, 41));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 51, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setToolTipText("120 Maximum characters");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPTweetStatusUpdateLayout = new javax.swing.GroupLayout(jPTweetStatusUpdate);
        jPTweetStatusUpdate.setLayout(jPTweetStatusUpdateLayout);
        jPTweetStatusUpdateLayout.setHorizontalGroup(
            jPTweetStatusUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTweetStatusUpdateLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPTweetStatusUpdateLayout.setVerticalGroup(
            jPTweetStatusUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTweetStatusUpdateLayout.createSequentialGroup()
                .addGroup(jPTweetStatusUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTweetStatusUpdateLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTweetStatusUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPTweetStatusUpdate.setBounds(0, 0, 1170, 79);
        jLayeredPane1.add(jPTweetStatusUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPBaseLayer.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 592, 1170, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBaseLayer, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBaseLayer, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleBTimeLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBTimeLineActionPerformed
            // TODO add your handling code here:
            jToggleBLists.setSelected(false);
            jToggleBMentions.setSelected(false);
            jToggleBMessages.setSelected(false);
            jToggleBProfiles.setSelected(false);
            jToggleBSearch.setSelected(false);
            jEPWeb.setContentType("text/html");
            jEPWeb.setBackground(Color.white);
            parseTweet();
    }//GEN-LAST:event_jToggleBTimeLineActionPerformed

    private void jToggleBMentionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBMentionsActionPerformed
        // TODO add your handling code here:
         jToggleBLists.setSelected(false);
        jToggleBTimeLine.setSelected(false);
        jToggleBMessages.setSelected(false);
        jToggleBProfiles.setSelected(false);
        jToggleBSearch.setSelected(false);
    }//GEN-LAST:event_jToggleBMentionsActionPerformed

    private void jToggleBMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBMessagesActionPerformed
        // TODO add your handling code here:
    jToggleBLists.setSelected(false);
   jToggleBTimeLine.setSelected(false);
   jToggleBMentions.setSelected(false);
   jToggleBProfiles.setSelected(false);
     jToggleBSearch.setSelected(false);
    }//GEN-LAST:event_jToggleBMessagesActionPerformed

    private void jToggleBListsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBListsActionPerformed
        // TODO add your handling code here:
   jToggleBTimeLine.setSelected(false);
   jToggleBMentions.setSelected(false);
       jToggleBMessages.setSelected(false);
        jToggleBProfiles.setSelected(false);
        jToggleBSearch.setSelected(false);
    }//GEN-LAST:event_jToggleBListsActionPerformed

    private void jToggleBProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBProfilesActionPerformed
        // TODO add your handling code here:
    jToggleBTimeLine.setSelected(false);
       jToggleBMentions.setSelected(false);
       jToggleBMessages.setSelected(false);
       jToggleBLists.setSelected(false);
       jToggleBSearch.setSelected(false);
    }//GEN-LAST:event_jToggleBProfilesActionPerformed

    private void jToggleBSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleBSearchActionPerformed
        // TODO add your handling code here:
       jToggleBTimeLine.setSelected(false);
       jToggleBMentions.setSelected(false);
       jToggleBMessages.setSelected(false);
       jToggleBLists.setSelected(false);
       jToggleBProfiles.setSelected(false);
    }//GEN-LAST:event_jToggleBSearchActionPerformed

private void jEPWebHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_jEPWebHyperlinkUpdate
    HyperlinkEvent.EventType type = evt.getEventType();
    final URL url = evt.getURL();

    if (type == HyperlinkEvent.EventType.ACTIVATED) {
        Runnable runner = new Runnable() {

            @Override
            public void run() {
                // Retain reference to original
                Document doc = jEPWeb.getDocument();
                try {
                    jEPWeb.setPage(url);
                } catch (IOException ioException) {
                    JOptionPane.showMessageDialog(null, "Error following link",
                            "Invalid link", JOptionPane.ERROR_MESSAGE);
                    jEPWeb.setDocument(doc);
                }
            }
        };
        EventQueue.invokeLater(runner);
    }
}//GEN-LAST:event_jEPWebHyperlinkUpdate



private void jBGotRequestTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGotRequestTokenActionPerformed
        System.out.println("In OK button clicked after getting number");
        try {
            client.oauth_verifier2=jTFrequestTokenResponse.getText();
            client.login_phase_2(requestTokenResponse);
                jTFrequestTokenResponse.setText("");//clear the text field
                        toggleUIButtons(true);//enable UI Buttons
                        jLayeredPane1.moveToFront(jPTweetStatusUpdate);
                        initUserInfo();//start populating UI with account info

        } catch (IOException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UniformInterfaceException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jBGotRequestTokenActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//History navigation button for travelling back in surfing time
    URL url=null;
        try {
            url = new URL(oldURL.toString());
        } catch (MalformedURLException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    Document doc =jEPWeb.getDocument();
      try {
        jEPWeb.setPage(url);
      } catch (IOException ioException) {
        System.out.println("Error following link");

        jEPWeb.setDocument(doc);
      }
      System.out.println("Exiting LoadAWebPage method");
}//GEN-LAST:event_jButton1ActionPerformed

     /***
     * @param toggleYN Allows Enable/Disable of UI Components
     * @return void
     */
private void toggleUIButtons(boolean toggleYN){
    System.out.println("In toggleButtons method");
    boolean toggle=toggleYN;
//jBPublishTweet.setEnabled(toggle);
jToggleBLists.setEnabled(toggle);
jToggleBMentions.setEnabled(toggle);
jToggleBMessages.setEnabled(toggle);
jToggleBProfiles.setEnabled(toggle);
jToggleBSearch.setEnabled(toggle);
jToggleBTimeLine.setEnabled(toggle);

}
private void  parseTweet(){
          StringBuilder str = new StringBuilder ("<table border='1' width='100%'>");
         str.append(strGetFriendsTimeline);
        str.append("</table>");

 String tokenisedTextString="";
       StringTokenizer st = new StringTokenizer(str.toString());

    while(st.hasMoreTokens())
    {
       String key = st.nextToken();
       if(key.startsWith("#")){
       key="<a href='https://twitter.com/#!/search?q=%23"+key+"'>"+key+"</a>";
       }
       else if(key.startsWith("@")){
       key="<a href='http://twitter.com/"+key+"'>"+key+"</a>";
       }
        else if(key.startsWith("http")){
       key="<a href='"+key+"'>"+key+"</a>";
       }
       else if(key.startsWith("https")){
       key="<a href='"+key+"'>"+key+"</a>";
        }
        tokenisedTextString+=key+" ";
        jEPWeb.setText(tokenisedTextString);
    }
}




    private void initUserInfo() throws MalformedURLException, IOException {
        System.out.println("In InitUserInfo Method");

        //Bring st back into scope at method level KD 15/07/11
        StatusType st = new StatusType();
        //Log in, get tokens, and append the tokens to the consumer and secret keys
        client.initOAuth();
        //Call getUserTimeline, get a list of statuses, pass the most recent
        //status as a StatusType object, and display the text of that object
        //in the JTextField
         Statuses statuses = client.getUserTimeline(Statuses.class, null, null, null, "1");
         st = statuses.getStatus().get(0);
        //try decoding the text before showing it in the ui 22/07/11 - KD
        jLLatestTweet.setText(st.getText().trim());

        //Get a UserType object from the StatusType object, get the URL of that
        //user's icon, and display that icon in the JLabel
          UserType user = st.getUser();
          String iconSrc = user.getProfileImageUrl();
          URL iconUrl = new URL(iconSrc);
          ImageIcon icon = new ImageIcon(iconUrl, user.getScreenName());
          jLUserIcon.setIcon(icon);
          jLTwitterHandle.setText(user.getScreenName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGotRequestToken;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JEditorPane jEPWeb;
    private javax.swing.JLabel jLLatestTweet;
    private javax.swing.JLabel jLStatusLabel;
    private javax.swing.JLabel jLTwitterHandle;
    private javax.swing.JLabel jLUserIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPBaseLayer;
    private javax.swing.JPanel jPGetVerifierNum;
    private javax.swing.JPanel jPPhotoHandle;
    private javax.swing.JPanel jPTweetStatusUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFrequestTokenResponse;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleBLists;
    private javax.swing.JToggleButton jToggleBMentions;
    private javax.swing.JToggleButton jToggleBMessages;
    private javax.swing.JToggleButton jToggleBProfiles;
    private javax.swing.JToggleButton jToggleBSearch;
    private javax.swing.JToggleButton jToggleBTimeLine;
    // End of variables declaration//GEN-END:variables
    /**
     * private TwitterClient client This points to the class below and gives
     * us access to a static TwitterClient object in memory
     */
    private TwitterClient client;

    static class TwitterClient {

        private WebResource webResource;
        private Client client;
        private static final String BASE_URI = "https://twitter.com";

        public TwitterClient() {
           System.out.println("In TwitterClient InnerClass Constructor");
            com.sun.jersey.api.client.config.ClientConfig config = new com.sun.jersey.api.client.config.DefaultClientConfig(); // SSL configuration
            config.getProperties().put(com.sun.jersey.client.urlconnection.HTTPSProperties.PROPERTY_HTTPS_PROPERTIES, new com.sun.jersey.client.urlconnection.HTTPSProperties(getHostnameVerifier(), getSSLContext()));
              client = Client.create(config);
            String resourcePath = "statuses";
            //change this as not all resources are a status
             //webResource = client.resource(BASE_URI).path(resourcePath);
            webResource = client.resource(BASE_URI);
        }
        private static final String OAUTH_BASE_URL = "http://twitter.com/oauth";
        /**
         * Please, specify the consumer_key string obtained from service API pages
         */
        private static final String CONSUMER_KEY = "uDgRAVEtjxsBtR52PqAA";
        /**
         * Please, specify the consumer_secret string obtained from service API pages
         */
        private static final String CONSUMER_SECRET = "85zAfuclWgW7cZTmgqVUq2JEicD6kV6sCOH6SIIZU";
      //  private String oauth_verifier;//retriev from dialog
        private OAuthParameters oauth_params;
        private OAuthSecrets oauth_secrets;
        private OAuthClientFilter oauth_filter;
        private String oauth_access_token;
        private String oauth_access_token_secret;
        String oauth_verifier2=null;//taken from webpage via OK button event


        //public void setResourcePath(String format) {
          //  String resourcePath = java.text.MessageFormat.format("statuses/user_timeline.{0}", new Object[]{format});
            //webResource = client.resource(BASE_URI).path(resourcePath);
        //}

        /**
         * @param responseType Class representing the response
         * @param since query parameter
         * @param since_id query parameter
         * @param page query parameter
         * @param count query parameter
         * @return response object (instance of responseType class)
         */
        //This function returns my tweets
        public <T> T getUserTimeline(Class<T> responseType, String since, String since_id, String page, String count) throws UniformInterfaceException {
            String[] queryParamNames = new String[]{"since", "since_id", "page", "count"};
            String[] queryParamValues = new String[]{since, since_id, page, "count"};
            return webResource.path("/statuses/user_timeline.xml").queryParams(getQueryOrFormParams(queryParamNames, queryParamValues)).accept(javax.ws.rs.core.MediaType.TEXT_XML).get(responseType);
        }
        //this function returns tweets that mention me
         public <T> T getMentions(Class<T> responseType, String since, String since_id, String page, String count) throws UniformInterfaceException {
            String[] queryParamNames = new String[]{"since", "since_id", "page", "count"};
            String[] queryParamValues = new String[]{since, since_id, page, "count"};
            return webResource.path("/statuses/mentions.xml").queryParams(getQueryOrFormParams(queryParamNames, queryParamValues)).accept(javax.ws.rs.core.MediaType.TEXT_XML).get(responseType);
        }

         public <T> T getAllLists(Class<T> responseType, String since, String since_id, String page) throws UniformInterfaceException {
            String[] queryParamNames = new String[]{"since", "since_id", "page"};
            String[] queryParamValues = new String[]{since, since_id, page};
            return webResource.path("/lists/all.xml").queryParams(getQueryOrFormParams(queryParamNames, queryParamValues)).accept(javax.ws.rs.core.MediaType.TEXT_XML).get(responseType);
        }

            //this function returns the tweets of people I follow
            public <T> T getFriendsTimeline(Class<T> responseType, String since, String since_id, String page, String count) throws UniformInterfaceException {
            String[] queryParamNames = new String[]{"since", "since_id", "page", "count"};
            String[] queryParamValues = new String[]{since, since_id, page, count};
            //updated endpoint as per twitter API change 19/07/11 -KD
            return webResource.path("/statuses/home_timeline.xml").queryParams(getQueryOrFormParams(queryParamNames, queryParamValues)).accept(javax.ws.rs.core.MediaType.TEXT_XML).get(responseType);
        }
            //this function allows me to update my status
            public <T> T updateStatus(Class<T> responseType, String status, String in_reply_to_status_id) throws UniformInterfaceException {
            String[] formParamNames = new String[]{"status", "in_reply_to_status_id"};
            String[] formParamValues = new String[]{status, in_reply_to_status_id};
            return webResource.path("/statuses/update.xml").type(javax.ws.rs.core.MediaType.APPLICATION_FORM_URLENCODED).post(responseType, getQueryOrFormParams(formParamNames, formParamValues));
        }
        private MultivaluedMap getQueryOrFormParams(String[] paramNames, String[] paramValues) {
            MultivaluedMap<String, String> qParams = new com.sun.jersey.api.representation.Form();//Debug this String String
            for (int i = 0; i < paramNames.length; i++) {
                if (paramValues[i] != null) {
                    qParams.add(paramNames[i], paramValues[i]);
                }
            }
            return qParams;
        }

        public void close() {
            client.destroy();
        }

        /**
         * You need to call this method at the beginning to authorize the application to work with user data.
         * The method obtains the OAuth access token string, that is appended to each API request later.
         */
        public void login() throws IOException, UniformInterfaceException {

            Form requestTokenResponse = getOAuthRequestToken();
            System.out.println("In login method phase 1 requestTokenResponse "+requestTokenResponse.toString());
            TwitterJFrame.requestTokenResponse=requestTokenResponse;//pass rTR to outter class so outer class can call loginPhase2
            String temp=getOAuthURL(requestTokenResponse);//playing ball with Jersey just to rob oAuthURL
            }

            //seperate these here
            public void login_phase_2(Form requestTokenResponse) throws IOException, UniformInterfaceException {
            System.out.println("In login_phase_2");
             String oauth_verifier = authorizeConsumer(requestTokenResponse);
            System.out.println("oauth_verifier= "+oauth_verifier);
            Form accessTokenResponse = getOAuthAccessToken(requestTokenResponse, oauth_verifier);
            System.out.println("OAuth Access Token= "+accessTokenResponse.toString());
            oauth_access_token_secret = accessTokenResponse.getFirst("oauth_token_secret");
            oauth_access_token = accessTokenResponse.getFirst("oauth_token");
             System.out.println("oauth_access_token_secret= "+oauth_access_token_secret+" oauth_access_token= "+oauth_access_token);
        }

        private Form getOAuthRequestToken() throws UniformInterfaceException {
            System.out.println("In client.getoAuthRequestToken method");
            WebResource resource = client.resource(OAUTH_BASE_URL).path("request_token");
            oauth_params = new OAuthParameters().consumerKey(CONSUMER_KEY).signatureMethod(com.sun.jersey.oauth.signature.HMAC_SHA1.NAME).version("1.0").nonce().timestamp();
            oauth_secrets = new OAuthSecrets().consumerSecret(CONSUMER_SECRET);
            oauth_filter = new OAuthClientFilter(client.getProviders(), oauth_params, oauth_secrets);
            resource.addFilter(oauth_filter);
            return resource.get(Form.class);
        }

        private Form getOAuthAccessToken(Form requestTokenResponse, String oauth_verifier) throws UniformInterfaceException {
            System.out.println("In client.getoAuthAccessToken method");
            WebResource resource = client.resource(OAUTH_BASE_URL).path("access_token");
            oauth_params.token(requestTokenResponse.getFirst("oauth_token")).signatureMethod(com.sun.jersey.oauth.signature.HMAC_SHA1.NAME).version("1.0").nonce().timestamp().verifier(oauth_verifier);
            oauth_secrets.tokenSecret(requestTokenResponse.getFirst("oauth_token_secret"));
            resource.addFilter(oauth_filter);
            return resource.get(Form.class);
        }

        /**
         * The method sets the OAuth parameters for webResource.
         * The method needs to be called after login() method, or when the webResource path is changed
         */
        public void initOAuth() {
            System.out.println("In client.initoAuth method");
            oauth_params = new OAuthParameters().consumerKey(CONSUMER_KEY).token(oauth_access_token).signatureMethod(com.sun.jersey.oauth.signature.HMAC_SHA1.NAME).version("1.0").nonce().timestamp();
            oauth_secrets = new OAuthSecrets().consumerSecret(CONSUMER_SECRET).tokenSecret(oauth_access_token_secret);
            oauth_filter = new OAuthClientFilter(client.getProviders(), oauth_params, oauth_secrets);
            webResource.addFilter(oauth_filter);
        }

        /**
         * The method increases OAuth nonce and timestamp parameters to make each request unique.
         * The method should be called when repetitive requests are sent to service API provider:
         * <pre>
         * client.initOauth();
         * client.getXXX(...);
         * client.makeOAuthRequestUnique();
         * client.getYYY(...);
         * client.makeOAuthRequestUnique();
         * client.getZZZ(...);
         * </pre>
         */
        public void makeOAuthRequestUnique() {
            System.out.println("In client.makeoAuthRequestsUnique method");
            if (oauth_params != null) {

                oauth_params.nonce().timestamp();
            }
        }

       private String getOAuthURL(Form requestTokenResponse)throws IOException{
           URL url =null;
           String strURLstr="";

            try {
              URI uri = new URI("http://twitter.com/oauth/authorize?oauth_token=" + requestTokenResponse.getFirst("oauth_token"));
                 url = uri.toURL();
                strURLstr=url.toString();
            } catch (java.net.URISyntaxException ex) {
            }
            TwitterJFrame.oAuthURL=url;//transfer oAuthURL from inner class to outter class
            System.out.println("In client.getOAuthURL url="+strURLstr);
       return strURLstr;
       }

        private java.lang.String authorizeConsumer(Form requestTokenResponse) throws IOException {
            String ov2=null;
            ov2=oauth_verifier2;
            System.out.println("In client.authoriseConnsumer method, oAuth VerifierNumber is: "+ov2);
            return ov2;
    }

        private HostnameVerifier getHostnameVerifier() {
            System.out.println("In client.getHostnameVerifier method");
            return new HostnameVerifier() {

                @Override
                public boolean verify(String hostname, javax.net.ssl.SSLSession sslSession) {
                    return true;
                }
            };
        }

        private SSLContext getSSLContext() {
            System.out.println("In client.getSSLContext method");
            javax.net.ssl.TrustManager x509 = new javax.net.ssl.X509TrustManager() {

                @Override
                public void checkClientTrusted(java.security.cert.X509Certificate[] arg0, String arg1) throws java.security.cert.CertificateException {
                    return;
                }

                @Override
                public void checkServerTrusted(java.security.cert.X509Certificate[] arg0, String arg1) throws java.security.cert.CertificateException {
                    return;
                }

                @Override
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return null;
                }
            };
            SSLContext ctx = null;
            try {
                ctx = SSLContext.getInstance("SSL");
                ctx.init(null, new javax.net.ssl.TrustManager[]{x509}, null);
            } catch (java.security.GeneralSecurityException ex) {
            }
            return ctx;
        }
    }
}